// mraa/src/app/scripture/scripture.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-scripture',
  standalone: true,
  imports: [],
  templateUrl: './scripture.component.html',
  styleUrl: './scripture.component.css'
})
export class ScriptureComponent {

}

<div>
        
    <blockquote className={styles.psalm}>
        For a thousand years in thy sight are but as yesterday when <br/>
        it is past, and as a watch in the night. <br/>
        <a href="https://www.churchofjesuschrist.org/study/scriptures/ot/ps/90?lang=eng#p4" target="_blank">Psalm 90:4</a>
    </blockquote>

    <blockquote className={styles.peter}>
        But, beloved, be not ignorant of this one thing, that one day <br/>
        is with the Lord as a thousand years, and a thousand years as <br/>
        one day. <br/>
        <a href="https://www.churchofjesuschrist.org/study/scriptures/nt/2-pet/3?lang=eng#p8" target="_blank">2 Peter 3:8</a>
    </blockquote>

    <blockquote className={styles.abraham}>
        And the Lord said unto me, by the Urim and Thummim, <br/>
        that Kolob was after the manner of the Lord, according to its <br/>
        times and seasons in the revolutions thereof; that one revolution <br/>
        was a day unto the Lord, after his manner of reckoning, <br/>
        it being one thousand years according to the time appointed <br/>
        unto that whereon thou standest. This is the reckoning of the <br/>
        Lord's time, according to the reckoning of Kolob. <br/>
        <a href="https://www.churchofjesuschrist.org/study/scriptures/pgp/abr/3?lang=eng#p4" target="_blank">Abaraham 3:4</a>
    </blockquote>

</div>

// app/components/scripture.tsx
import Link from "next/link";

export default function Scripture() {
    return (

        <div>
            <blockquote>
                For a thousand years in thy sight are but as yesterday when <br/>
                it is past, and as a watch in the night. <br/>
                <Link href="https://www.churchofjesuschrist.org/study/scriptures/ot/ps/90?lang=eng" target="_blank">Psalm 90:4</Link>
            </blockquote>

            <blockquote>
                But, beloved, be not ignorant of this thing, that one day <br/>
                is with the Lord as a thousand years, and a thousand years as <br/>
                one day. <br/>
                <Link href="https://www.churchofjesuschrist.org/study/scriptures/nt/2-pet/3?lang=eng" target="_blank">2 Peter 3:8</Link>
            </blockquote>

            <blockquote>
                And the Lord said unto me, by the Urim and Thummim, <br/>
                that Kolob was after the manner of the Lord, according to its <br/>
                times and seasons in the revolutions thereof; that one revolu- <br/>
                tion was a day unto the Lord, after his manner of reckoning, <br/>
                it being one thousand years according to the time appointed <br/>
                unto that whereon thou standest. This is the reckoning of the <br/>
                Lord's time, according to the reckoning of Kolob. <br/>
                <Link href="https://www.churchofjesuschrist.org/study/scriptures/pgp/abr/3?lang=eng" target="_blank">Abraham 3:4</Link>
            </blockquote>

        </div>

    );
}
