// vue/src/App.vue
<script setup>
import HeaderComp from "./components/HeaderComp.vue";
import ScriptureComp from "./components/ScriptureComp.vue";
import DateComp from "./components/DateComp.vue";
import AgeComp from "./components/AgeComp.vue";
import FooterComp from "./components/FooterComp.vue";
</script>

<template>
    <HeaderComp />
    <ScriptureComp />
    <DateComp />
    <AgeComp />
    <FooterComp />
</template>

<style scoped></style>

// app/page.tsx
import HeaderComp from "./components/header-comp";
import ScriptureComp from "./components/scripture-comp";
import DateComp from "./components/date-comp";
import FooterComp from "./components/footer-comp";

export default function Home() {
  return (
    <>
      <HeaderComp />
      <ScriptureComp />
      <DateComp />
      <FooterComp />
    </>
  );
}
